server:
  port: 8081

zuul:
  routes:
    back:
      url: http://127.0.0.1:8080/
      path: /back/**
    mapi:
      url: https://mapi.cgtn.com/mobileapp
      path: /mapi/**

spring:
  freemarker:
    cache: false
    templateLoaderPath:
      - "classpath:/templates/"
      - "file:templates/"


ribbon:
  eureka:
    enabled: false